create table if not exists blog (
    id bigint generated by default as identity,
    body varchar(255),
    name varchar(255),
    subject varchar(255),
    primary key (id)
    );
create table if not exists photo (
    id uuid default random_uuid() not null,
    content blob,
    content_type varchar(255),
    filename varchar(255),
    blog_id bigint,
    primary key (id),
    foreign key (blog_id) references blog
    );

